# DATABASE H2
spring:
  h2:
    console:
      enabled: true
      path: /h2-console
      settings:
        trace: false
        web-allow-others: false

  datasource:
    url: jdbc:h2:mem:reservaDb;INIT=RUNSCRIPT FROM 'classpath:data.sql'
    username: rs
    password:
    driver-class-name: org.h2.Driver
    initialization-mode: always

  jpa:
    generate-ddl: true
    hibernate:
      ddl-auto: create
